### ISSUE TITLE
Version 2.7.2 give a java.lang.NoSuchMethodError on AnnotatedMember.getType

### ISSUE THREAD

**Issue by islemus** [FasterXML/jackson-module-jaxb-annotations#57]
Using the following dependencies with a customer object mapper using jersey / wildfly 10
jackson-core@2.7.2
jackson-databind@2.7.2
jackson-annotations@2.7.2
jackson-module-jaxb-annotations@2.7.2

I have the following error when posting/putting on my web service when using a custom object mapper (see below)

java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.getType()Lcom/fasterxml/jackson/databind/JavaType;

The same case works fine using the version 2.6 of all the above dependencies 

```java
@Provider
public class JacksonConfiguration implements ContextResolver<ObjectMapper>
{
	private final ObjectMapper objectMapper;

	public JacksonConfiguration() throws Exception
	{
		objectMapper = new ObjectMapper();
		objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
		objectMapper.setTimeZone(TimeZone.getDefault());

		AnnotationIntrospector aiJaxb = new JaxbAnnotationIntrospector(TypeFactory.defaultInstance());
		AnnotationIntrospector aiJackson = new JacksonAnnotationIntrospector();

		// first Jaxb, second Jackson annotations
		objectMapper.setAnnotationIntrospector(AnnotationIntrospector.pair(aiJaxb, aiJackson));
	}

	@Override
	public ObjectMapper getContext(Class<?> arg0)
	{
		return objectMapper;
	}
}

```

**Comment by cowtowncoder** [comment]
@islemus There is no version 2.7, but I assume you may mean 2.7.0.
If so, make sure to upgrade to 2.7.2 (of `jackson-databind` especually) and that might solve your issue.

**Comment by islemus** [comment]
Sorry for the typos, it was the 2.7.2 of all the dependencies (using a maven property)

When setting the property to 2.6.5 everything works fine

**Comment by cowtowncoder** [comment]
@islemus Minor versions of components do need to agree. I can not reproduce your problem, and the error stems from incompatible versions. Aside from the common problem of accidentally having conflicting versions in the classpath (that is, both 2.7.2 and some older version), possibilities include using classes from other libraries or frameworks that may be compiled against older version of Jackson.

**Comment by cowtowncoder** [comment]
I would need full stack trace to make sure exactly where the problem occurs, but I think there is a good chance it may have been resolved in 2.7.3 or 2.7.4, so the first step would be reproduction with 2.7.4.
If that still happens, I need stack trace to investigate further. At this point will close, assuming problem is resolved, but please re-open if it is reproducible, and stack trace is available as additional information.

**Comment by cipous** [comment]
I had same problem, when there was recursion in my mapping. In 2.6.1 it threw readable exception, in 2.7.2 or 2.7.4 it throws no such method exception.

**Comment by cowtowncoder** [comment]
At this point the crucial point to know is that minor version of Jackson used does have to match minor version of Jackson that was used to compile framework.
